language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8 software-properties-common libgl1-mesa-dev libglu1-mesa-dev libglew-dev libsdl2-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

before_script:
  - bash tool/lin/bin/premake5.sh --cc=gcc --no-example --no-tutorial gmake
  - make config=linux64_release
  - cd test/bin/linux64/release

script: ./minko-tests

branches:
  only:
    - master
    - dev

os:
  - linux
